"""
Local-only script — NOT deployed to Snowflake.

Run this script whenever the CSV changes, then paste the output into dealers.py.

Usage:
    python generate_dealers.py
"""

import csv
from datetime import date
from pathlib import Path

CSV_PATH = Path(__file__).parent / "data" / "Competitive Insights _ Beta Dealer Sign Ups - Finalized Dealer List (DO NOT EDIT).csv"


def parse_start_date(ar: str) -> str:
    if ar.lower().startswith("added on"):
        month, day = ar.split("on")[1].strip().split("/")
        return date(2026, int(month), int(day)).isoformat()
    return "2026-05-21"


def main():
    active = []

    with open(CSV_PATH) as f:
        reader = csv.reader(f)
        for _ in range(3):
            next(reader)
        headers = next(reader)
        spid_idx = headers.index("SPID")
        ar_idx = headers.index("Added/Removed")

        for row in reader:
            if not row or not row[spid_idx].strip():
                continue
            ar = row[ar_idx].strip() if ar_idx < len(row) else ""
            if ar.lower().startswith("removed"):
                continue
            active.append((int(row[spid_idx].strip()), parse_start_date(ar)))

    dealer_list = ",".join(str(spid) for spid, _ in active)

    print(f'# {len(active)} active dealers — generated by generate_dealers.py')
    print(f'DEALER_LIST = "{dealer_list}"')
    print()
    print("DEALER_DATES = {")
    for spid, start in active:
        print(f'    {spid}: "{start}",')
    print("}")


if __name__ == "__main__":
    main()
