"""
Local-only script — NOT deployed to Snowflake.

Run this script whenever any CSV changes, then paste the output into dealers.py.

Usage:
    python generate_dealers.py
"""

import csv
from datetime import date
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"

BETA_CSV         = DATA_DIR / "Competitive Insights _ Beta Dealer Sign Ups - Finalized Dealer List (DO NOT EDIT).csv"
AUTONATION_CSV   = DATA_DIR / "Competitive Insights _ Beta Dealer Sign Ups - AutoNation Beta Dealers.csv"
KEN_GRAFF_CSV    = DATA_DIR / "Competitive Insights _ Beta Dealer Sign Ups - Ken Graff Automotive Dealers.csv"
SHOPPER_SIG_CSV  = DATA_DIR / "Competitive Insights _ Beta Dealer Sign Ups - Shopper Signals Signups.csv"


def parse_date_str(s: str) -> str:
    """Parse 'M/D', 'MM/DD/YYYY' date strings to ISO format. Falls back to 2026-05-21."""
    s = s.strip()
    if not s:
        return "2026-05-21"
    parts = s.split("/")
    try:
        if len(parts) == 3:
            month, day, year = int(parts[0]), int(parts[1]), int(parts[2])
            return date(year, month, day).isoformat()
        elif len(parts) == 2:
            month, day = int(parts[0]), int(parts[1])
            return date(2026, month, day).isoformat()
    except (ValueError, TypeError):
        pass
    return "2026-05-21"


def parse_beta_csv() -> list[tuple[int, str]]:
    """Parse original beta list (3 blank rows then header)."""
    active = []
    with open(BETA_CSV) as f:
        reader = csv.reader(f)
        for _ in range(3):
            next(reader)
        headers = next(reader)
        spid_idx = headers.index("SPID")
        ar_idx = headers.index("Added/Removed")

        for row in reader:
            if not row or not row[spid_idx].strip():
                continue
            ar = row[ar_idx].strip() if ar_idx < len(row) else ""
            if ar.lower().startswith("removed"):
                continue
            raw_date = ar.split("on")[-1].strip() if ar.lower().startswith("added on") else ""
            active.append((int(row[spid_idx].strip()), parse_date_str(raw_date)))
    return active


def parse_autonation_csv() -> list[tuple[int, str]]:
    """Parse AutoNation CSV (1-row header: Store Name, SpID, Added to Beta)."""
    active = []
    with open(AUTONATION_CSV) as f:
        reader = csv.reader(f)
        headers = next(reader)
        spid_idx = headers.index("SpID")
        date_idx = headers.index("Added to Beta")

        for row in reader:
            if not row or not row[spid_idx].strip():
                continue
            spid = row[spid_idx].strip()
            if not spid.isdigit():
                continue
            date_str = row[date_idx].strip() if date_idx < len(row) else ""
            active.append((int(spid), parse_date_str(date_str)))
    return active


def parse_generic_csv(filepath: Path) -> list[tuple[int, str]]:
    """Parse CSVs with 1 blank row then a header containing SPID + ADDED TO BETA."""
    active = []
    with open(filepath) as f:
        reader = csv.reader(f)
        next(reader)  # skip blank row
        headers = next(reader)
        spid_idx = headers.index("SPID")
        date_idx = headers.index("ADDED TO BETA")

        for row in reader:
            if not row or not row[spid_idx].strip():
                continue
            spid = row[spid_idx].strip()
            if not spid.isdigit():
                continue
            date_str = row[date_idx].strip() if date_idx < len(row) else ""
            active.append((int(spid), parse_date_str(date_str)))
    return active


def emit_cohort(var_prefix: str, label: str, records: list[tuple[int, str]]) -> None:
    dealer_list = ",".join(str(spid) for spid, _ in records)
    print(f"# {len(records)} dealers — {label}")
    print(f'{var_prefix}_LIST = "{dealer_list}"')
    print()
    print(f"{var_prefix}_DATES = {{")
    for spid, start in records:
        print(f'    {spid}: "{start}",')
    print("}")
    print()


def main():
    beta          = parse_beta_csv()
    autonation    = parse_autonation_csv()
    ken_graff     = parse_generic_csv(KEN_GRAFF_CSV)
    shopper_sigs  = parse_generic_csv(SHOPPER_SIG_CSV)

    print("# Generated by generate_dealers.py — do not edit by hand.")
    print("# To regenerate: python generate_dealers.py, then paste output here.")
    print()
    emit_cohort("DEALER",          "Beta Dealers (finalized list)",       beta)
    emit_cohort("AUTONATION",      "AutoNation Beta Dealers",             autonation)
    emit_cohort("KEN_GRAFF",       "Ken Garff Automotive Dealers",        ken_graff)
    emit_cohort("SHOPPER_SIGNALS", "Shopper Signals Signups",             shopper_sigs)


if __name__ == "__main__":
    main()
